### ISSUE TITLE
Formatação das Referências Bibliográficas

### ISSUE THREAD

**Issue by fabionl** [thiagodnf/uecetex2#1]
Thiago,

Estou tendo um problema que não estou conseguindo resolver. As referências bibliográficas estão saindo com recuo e não estou conseguindo retirá-lo. Como posso fazer isso? Já olhei no no preambulo.tex e está com recuo=0cm. Não to encontrando outra forma. :(

Formato: Dissertação
Compilador: Pandoc
S.O: Mac OSX

Muito obrigado pelo trabalho, tá ajudando muito. :)

**Comment by thiagodnf** [comment]
Olá Fábio,

Você poderia enviar o código para que eu pudesse compilar aqui?

**Comment by fabionl** [comment]
Olá @thiagodnf,

qual o código que você precisa?

**Comment by thiagodnf** [comment]
Seria interesse você mandar o seu projeto com pelo menos o básico para que eu pudesse ver o erro. Não precisa ser todo mas o mínimo para que o erro fosse simulado. Eu sei que no Windows e Linux está funcionando mas não testei no osx. Eu gostaria de ver se o erro é do template (rodando aqui no linux e windows) ou se é alguma coisa do compilador utilizado. 

Se você baixar o template original,  sem nenhuma modificação, o pdf é gerado corretamente?

**Comment by fabionl** [comment]
@thiagodnf,

gerei o documento.tex como você sugeriu, e não saiu as referências.

Comando que utilizei foi o seguinte:

**Comment by fabionl** [comment]
@thiagodnf,

A dissertação tá sendo escrita com um misto de Markdown, com alguns elementos em Latex (principalmente figuras).

Com o Makefile eu consegui gerar o documento.tex mas não consegui gerá-lo utilizando o pandoc. :disappointed: 

O comando que utilizei foi o seguinte:
pandoc  --latex-engine=xelatex -SRs --normalize --filter=pandoc-citeproc  -o ./documento.tex.pdf documento.tex

Erro que recebi: (Não muito informativo)

! Undefined control sequence.
l.52 \imprimircapa

pandoc: Error producing PDF from TeX source

**Comment by thiagodnf** [comment]
Olá @fabionl 

Eu não conhecia esse pandoc. Eu perguntei a algumas pessoas que tem mac e elas disseram utilizar o MacTeX http://www.tug.org/mactex/. Será que o problema é o seu compilador/? Existe alguma necessidade de compilar usando o pandoc?

Além disso, esse erro: 
! Undefined control sequence.
l.52 \imprimircapa

Parece que você não incluiu o pacote uecetex2?

**Comment by fabionl** [comment]
Olá @thiagodnf,

O motivo que me fez utilizar o pandoc é que eu escrevo 90% do texto em Markdown, utilizo o Latex apenas para solucionar questões específicas, como a inclusão de figuras no padrão que a UECE exige. Além disso, preciso ter condições de exportar para o Word para que o meu orientador possa trabalhar, porém pretendo exportar para PDF quando finalizar.

Leve em conta que faço mestrado em Administração, e Latex não faz parte da minha formação, dei um salto enorme ao utilizá-lo (mesmo que de forma indireta) no meu trabalho. Sou o único que tomou esse rumo na minha turma. rs

Se achar que faz diferença, posso montar algo pequeno que represente o que estou tentando compilar. (Não faz muito sentido mandar 50 páginas escritas, rs).

Acho que inclui o pacote uecetex2, mas vou rever isso.

**Comment by thiagodnf** [comment]
Nunca trabalhei com latex codificando em Markdown. Se tiver tempo mande um modelo simples do que você está tentando fazer para que eu possa simular o problema aqui.

**Comment by fabionl** [comment]
Não consegui compilar o documento.tex.

Segue um arquivo que sou capaz de compilar. Incluso está o PDF criado.

https://www.dropbox.com/s/ycs2mdjbn1gdrnx/Justificativa.md.zip?dl=0

Obrigado pela atenção. :smile:

**Comment by thiagodnf** [comment]
Olá Fábio,

Acho que encontrei o problema. Tentei gerar o .tex no lugar do .pdf para ver o que ele faz antes de gerar o pdf. Descobri que ele cria a referência de forma estática no texto antes de gerar. Por exemplo, no lugar de no texto aparecer:
```
" 800 milhões nas primeiras 24 horas de lançamento \cite{GEDIGames2014}."
```
aparece isso:
```
" 800 milhões nas primeiras 24 horas de lançamento (GEDIGames 2014)."
```
Além disso ele coloca no texto, também de forma estática, a referência. Fica assim:

```
225 milhões e faturou US\$ 800 milhões nas primeiras 24 horas de
lançamento (GEDIGames 2014).

GEDIGames. 2014. ``Relatório Final: Mapeamento Da Indústria Brasileira E
Global de Jogos Digitais.'' São Paulo: Núcleo de Política e Gestão
Tecnológica - PGT/USP.
```

Tá vendo vendo que tudo está estático? O bibtex que deveria gerar a página de referência mas pelo visto não é isso que está acontecendo. O próprio pandoc está gerando para você, formatando e colocando no texto.

A minha sugestão é você utilizar a forma padrão de citação do latex e deixar que o bibtex se encarregue de gerar a página de referência. Por exemplo, troque o [@GEDIGames2014] por \cite{GEDIGames2014}.

Acho que assim seu código irá funcionar normalmente. Tenta fazer com um exemplo e veja se a referência sai corretamente.

**Comment by fabionl** [comment]
@thiagodnf,
Infelizmente não deu certo. O problema é que o pandoc não gera a referência dessa forma aparece "??" no lugar dos autores. E não gera a bibliografia. Dei uma pesquisa e o Pandoc só trabalharia com o bibtex se fosse gerado um arquivo Latex. E eu preciso gerar arquivos Word também, não posso trabalhar apenas com PDF e/ou Latex. :(

Seria possível eu colocar algum comando para mudar a formatação dos parágrafos apenas na bibliografia?

Muito obrigado pela atenção que você tá me dispensando. Tá ajudando muito.

**Comment by thiagodnf** [comment]
@fabionl 

Eu acho que entendi o que você quer fazer, entretanto eu não quero te desanimar. Eu não sei se existe uma ferramenta que faça exatamente isso que você quer fazer (markdown para pdf e word usando um template em latex). Tentei aqui alguns parâmetros no pandoc e nenhuma delas conseguiu gerar o .docx com o template do uecetex2. 

Você conseguiu gerar? Se sim como você fez?

A formatação errada do parágrafo da referencia é gerada pelo pandoc. Eu não sei como alterar.

**Comment by fabionl** [comment]
@thiagodnf,
O Word dá pra gerar a partir de um template Word. Atualmente estou conseguindo trabalhar dessa forma (embora esteja me causando alguns problemas contornáveis). O principal pra mim é que a partir do texto em Markdown eu consiga gerar o documento Word e o PDF (Não precisa ser a partir do template em latex para o Word). Por isso que usar \cite me gera problemas (Não funcionaria na hora de exportar para o Word).

Eu entendi por uma das tuas respostas, que o pandoc tá gerando um parágrafo normal nas referências, que é o que está causando o problema de formatação. Seria possível alterar essa formatação de parágrafo apenas nessa seção? (O equivalente a colocar dentro de um bloco BEGIN..END)

Desculpa a dúvida básica de Latex, mas por incrível que pareça, não encontro esse tipo de informação na net.

**Comment by thiagodnf** [comment]
@fabionl 

Realmente o que você quer não tem como fazer (pelo menos não faço a mínima ideia de como resolver esse problema). Quanto o latex, você pode retirar o recuo usando o comando logo após o capítulo "Referências"

```tex
\setlength{\parindent}{0pt}
```

Atenção! Isso é uma gambiarra para resolver o seu problema e não fica de acordo com as regras da biblioteca. Acho que nem visualmente fica legal.

```
Brito, Luiz Artur Ledur, and Flávio Carvalho De Vasconcelos. 2004. “A Heterogeneidade Do De-
sempenho, Suas Causas E O Conceito de Vantagem Competitiva: Proposta de Uma Métrica.” Re-
vista de Administração Contemporânea 8: 107–129. doi:10.1590/S1415-65552004000500007.
GEDIGames. 2014. “Relatório Final: Mapeamento Da Indústria Brasileira E Global de Jogos
Digitais.” São Paulo: Núcleo de Política e Gestão Tecnológica - PGT/USP.
```

O pandoc gera para word mas fica fora da formatação da uece totalmente.

**Comment by fabionl** [comment]
@thiagodnf,

Para gerar no formato ABNT, existe um arquivo .csl (formato do Zotero) que faz isso. Tá inclusive no github.

O comando funcionou perfeitamente.

A Propósito, tem um projeto que parece promissor, vale a pena acompanhá-lo: http://scholarlymarkdown.com/

Mais uma vez, muito obrigado pela tua disponibilidade em ajudar. :smile: 

grande abraço.

**Comment by fabionl** [comment]
Olá Tiago, Perdão por reabrir essa issue. :(

Ainda tenho uns probleminhas de formatação na bibliograifa.

1) Links muito longos ultrapassam a margem direita da página e inclusive saindo da página (link fica incompleto)
2) Como adicionar espaço entre cada referência? (digamos o equivalente a 1 linha entre cada referência)

Segue abaixo uma página de exemplo.

![dissertacao - problema formatacao bibliografia](https://cloud.githubusercontent.com/assets/955353/7897812/5a91e7e6-06c1-11e5-8207-d4f1a9b89b52.jpg)

**Comment by thiagodnf** [comment]
Olá Fábio,

Testei aqui o uecetex e vi que ele gera a quebra de link corretamente e deixa o espaço correto entre as entradas da bibliografia mas no teu caso pelo visto não funcionou devido o método que você utiliza para gerar o PDF.

Dá uma olhada nesse link http://stackoverflow.com/questions/2640111/url-latex-linebreak-problem para ver se tu consegue quebrar a url corretamente.

No caso do espaçamento entre linhas, tente colocar isso no latex

\setlength{\bibitemsep}{10pt}

**Comment by fabionl** [comment]
Consegui usando:

\setlength{\parskip}{10pt}

Quanto à url, com os comandos abaixo não deu certo:

\usepackage{hyperref}
\usepackage{breakurl}

Resolvi com '\sloppy' na bibliografia.

Obrigado mais uma vez pela ajuda. :)
