### ISSUE TITLE
Adequação as normas da UECE

### ISSUE THREAD

**Issue by davimonteiro** [thiagodnf/uecetex2#13]
Bom dia, Thiago.

Fui entregar a versão final da dissertação; entretanto, a bibliotecária relatou alguns problemas no documento. Por exemplo:
- Colocar os nomes dos apêndices em maiúsculo no sumário do documento
- Inserir a fonte nas listagens de código assim como acontece nas figuras e tabelas

Outro erro apontado pela bibliotecária foi a formação das referências. Pelo que entendi, existem diversos erros (e.g., ordem dos elementos essenciais e opcionais, o que deve ser negritado e o que deve estar em maiúsculo) sobre formação em diversos tipos de referências (e.g., artigos, periódicos, livros, entre outros). Alguns alunos do mestrado que entregaram suas dissertações recentemente tiveram que formatar as referências no MS Word, converter para PDF e inserir diretamente no documento original da dissertação.

Devo fazer isso nos próximos dias e documentar aqui o que foi necessário fazer. Seria interessante analisar a possibilidade de rever a formatação das referências no template para que novos mestrandos não passem por isso.

Atenciosamente,
Davi Monteiro.

**Comment by davimonteiro** [comment]
Sugestão de correção:

% Define o titulo no sumario do Apendice para nao negrito
\newcommand{\apendice}[1]{\chapter{\normalfont\uppercase{#1}}}

**Comment by thiagodnf** [comment]
Olá @davimonteiro 

Fiz a sua sugestão tanto no apêndice quanto no anexo. Muito obrigado

_"Inserir a fonte nas listagens de código assim como acontece nas figuras e tabelas"_
Não consegui fazer ainda. Pelo o que eu andei lendo  aqui https://groups.google.com/forum/#!topic/latex-br/tFNZaiCeLgM acho que vai ser um pouco complicado. 

Com relação ao restante vai ser um pouco mais complicado porque tem que fazer uma analise com calma comparando o modelo da UECE com o do abntex  e isso vai tomar um pouco de tempo.
