### ISSUE TITLE
Citações com caracteres especiais (ç,à,â,ó,ô, e afins) ficam minusculas!

### ISSUE THREAD

**Issue by HerculesCrato** [thiagodnf/uecetex2#18]
Por alguma razão não tenho conseguido mesmo mudando os pacotes de fonte a formação correta para as citações onde as letras especiais estão ficando minusculas. Por exemplo " ...segundo SANSãO (2013..." "..... para CONGREçO NACIONAL (2020)...." "..... de acordo com CONSUêLO (2017)......" alguma sugestão?

**Comment by thiagodnf** [comment]
Olá @HerculesCrato tudo bem?

Tente substituir todos os acentos por:

{\'e}
{\^e}
{\'a}
...
e assim por diante. 

http://www.bibtex.org/SpecialSymbols/

Testei aqui e funcionou nas referencias e no texto. 
Veja se funciona para você

**Comment by HerculesCrato** [comment]
Perfeito resolvido o problema, muito obrigado. O ç usando \c{c} da para resolver e para outras formas, como por exemplos bibliografias rusas e indianas eu usei esses aqui https://tex.stackexchange.com/questions/311776/using-ce-and-other-special-characters-in-bib-files-with-pdflatexbiblatexbi e https://tex.stackexchange.com/questions/57743/how-to-write-%C3%A4-and-other-umlauts-and-accented-letters-in-bibliography

**Comment by thiagodnf** [comment]
Obrigado pelo feedback Hercules.
