### ISSUE TITLE
Gênero do Coorientador é atribuído pelo gênero do Orientador

### ISSUE THREAD

**Issue by flalvess** [thiagodnf/uecetex2#2]
O erro é apresentado pelo uso da variável de controle de gênero do orientador no coorientador.
É fácil de ser encontrado, no diretório lib, no arquivo uecetex2.sty, nas linhas 210 e 226. Nos comandos "\artigocoorientador" e "\artigocoorientadorcomparenteses" utilizam como variável "uecetex2@orientadorfeminino", onde deveria ser "uecetex2@coorientadorfeminino".

**Comment by duanyrf** [comment]
O problema encontra-se nas linhas destacadas na imagem em anexo.
![bug - orientadores generos diferentes](https://cloud.githubusercontent.com/assets/2049689/14183793/6e5a4e94-f748-11e5-861a-89d7aa7b2dbf.png)

**Comment by thiagodnf** [comment]
Obrigado pelo feedback @flalvess  e @duanyrf 
Correção já foi commitada. 

Ver https://github.com/thiagodnf/uecetex2/commit/6b5363f0b5bc5e9dadf12f5951936a779940045a
