### ISSUE TITLE
Formatação desalinhada com as exigências da biblioteca

### ISSUE THREAD

**Issue by jeancsanchez** [thiagodnf/uecetex2#21]
Olá @thiagodnf,

Estou usando esse template para fazer minha monografia da pós graduação. 

Após a submissão à biblioteca a mesma informou alguns erros na formatação do trabalho. Corrigi a maioria, mas agora não consigo avançar. 

Poderia me ajudar a fazer essas duas alterações?
<img width="459" alt="Screen Shot 2020-09-11 at 18 41 58" src="https://user-images.githubusercontent.com/11152015/92975556-5eddd480-f43d-11ea-8b22-9d34083e27ad.png">

**Comment by ItaloYeltsin** [comment]
Vi aqui no meu trabalho como eu fiz, vou mandar um fix pro @thiagodnf mergear

**Comment by thiagodnf** [comment]
O fix do @ItaloYeltsin nunca chegou =D 

Olá @jeancsanchez , você ainda tem o documento antigo que a biblioteca dizia está em outra fonte? 
Calibri não é a font do word?

**Comment by ItaloYeltsin** [comment]
Opa, a noite eu mando, meu caro!
