### ISSUE TITLE
Erro: Lista de código-fonte e abreviaturas e siglas.

### ISSUE THREAD

**Issue by Raul-rx7** [thiagodnf/uecetex2#22]
Ao compilar o arquivo, no pdf não aparece a lista de abreviaturas e siglas e a lista de código-fonte fica bugada(ex: o nome Código-fonte 1 fica por cima do caption.).

**Comment by thiagodnf** [comment]
Olá @Raul-rx7 

Você resolveu esse problema?

Eu sei que para gerar a lista de abreviatures vc precisa usar a opção "Glossary" do texstudio e com[ilar o documento novamente. Para que isso funcione, vc precisa ter instalado o perl no seu computador.

**Comment by Raul-rx7** [comment]
Olá @thiagodnf 

Resolvi o problema da lista de abreviaturas fazendo exatamente o que você recomendou.
A lista de código-fonte continuou bugada, porém resolvi retira-la, pois o foco de minha pesquisa é em materiais, utiliizo o Python apenas pra me ajudar na caracterização dos tais materiais, sendo uma sutil aplicação de visualização de dados. 
Abraços.

**Comment by thiagodnf** [comment]
Obrigado pelo feedback @Raul-rx7
