### ISSUE TITLE
Bug na Numeração das Tabelas: A lista de tabelas começa com a Tabela 2, sendo essa a primeira tabela.

### ISSUE THREAD

**Issue by Raul-rx7** [thiagodnf/uecetex2#24]
A Lista de Tabelas começa numerando a primeira tabela como "Tabela 2". Dessa forma, 

![tabela-bugada](https://user-images.githubusercontent.com/72898972/99190067-3c20b280-2743-11eb-956f-9ab36b636008.png)

na verdade a Tabela 1 não é excluída, apenas começa sendo chamad de tabela 2. 

Como isso pode ser corrigido?

**Comment by thiagodnf** [comment]
Olá @Raul-rx7 

Eu acabei de reinstalar o miktex no meu pc e compilei o uecetex novamente. A lista de tabela está com a numeração correta. 
Porém, eu tive o mesmo problema quando estava criando o uecetex.  A solução foi alterar o contador dentro do .sty para forçar ele a começar pelo número correto.

Você poderia tentar atualizar o teu miktex para ver se atualizando os pacotes esse problema eh resolvido?

Obrigado pelo feedback.

**Comment by Raul-rx7** [comment]
> Olá @Raul-rx7
> 
> Eu acabei de reinstalar o miktex no meu pc e compilei o uecetex novamente. A lista de tabela está com a numeração correta.
> Porém, eu tive o mesmo problema quando estava criando o uecetex. A solução foi alterar o contador dentro do .sty para forçar ele a começar pelo número correto.
> 
> Você poderia tentar atualizar o teu miktex para ver se atualizando os pacotes esse problema eh resolvido?
> 
> Obrigado pelo feedback.

Bom dia, @thiagodnf 

Então, na verdade utilizo o TeXstudio no ubuntu, porém fiz o procedimento que você recomendou, mas nada mudou. Como seria o procedimento no arquivo .sty, para forçar ele começar pelo número correto ? Talvez dê certo. Ah  esqueci de mencionar (peço perdão) que estou trabalhando com a opção de TCC da Graduação. 

Aguardo resposta, meu bom. 
Abraços.

**Comment by thiagodnf** [comment]
Ola @Raul-rx7 

Dentro do seguinte arquivo:

https://github.com/thiagodnf/uecetex2/blob/master/lib/uecetex2.sty

Você tem a seguinte linha:

```tex
% Numeracao da tabela comeca em 1
\setcounter{table}{0}
```

Altere o valor de 0 para -1 e compile novamente o documento. Se eu não me engano foi isso. 

Tenho a leve impressão que o problema seja porque você tem algum pacote do latex desatualizado. 
Como o uecetex2 é baseado no abntex2, acho que vale a pena conferir se você tem a versão mais atualizada da biblioteca.

Aqui a versão no CTAN do abntex2

https://www.ctan.org/pkg/abntex2

Aqui a versão que tenho instalada no computador 

![image](https://user-images.githubusercontent.com/114015/100113110-f9936000-2e3d-11eb-839d-7b9d5fe33d18.png)

**Comment by Raul-rx7** [comment]
Olá, @thiagodnf 
Obrigado pela orientação.
A versão do meu abntex2 está atualizada. Consegui resolver o problema trocando o 0 por -1. 
Está sendo muito legal utilizar o template, tem me ajudado muito. Se futuramente me deparar com outros problemas, recorrerei a você! haha 
Grande abraço.

**Comment by thiagodnf** [comment]
Muito obrigado pelo feedback @Raul-rx7 . Desculpe a demora para responder.

Qualquer coisa, é só abrir uma nova issue. Abraços
