### ISSUE TITLE
Como consigo editar os dados do sumário?

### ISSUE THREAD

**Issue by marcosalves89** [thiagodnf/uecetex2#3]
Olá,
gostaria de saber como faço pra editar os dados do sumário, pois não aparece o elemento como arquivo pra eu editar.
Obrigado!

**Comment by thiagodnf** [comment]
Olá Marcos,

O sumário é gerado automaticamente mas eu acho que tem como esconder algumas entradas dele.

O que exatamente você quer fazer?

**Comment by thiagodnf** [comment]
Olá @marcosalves89 Tudo bem?

Conseguiu resolver o seu problema?
