### ISSUE TITLE
Tabelas iniciam em 2.

### ISSUE THREAD

**Issue by Renato2012** [thiagodnf/uecetex2#30]
É necessário alterar a linha:
\setcounter{table}{0} linha [370](https://github.com/thiagodnf/uecetex2/blob/master/lib/uecetex2.sty#L370) no arquivo uecetex2.sty
para
\setcounter{table}{-1} % -1 para iniciar contador em 1.
Para tabelas iniciarem em 1.

**Comment by thiagodnf** [comment]
Obrigado @Renato2012 

Você poderia informar qual versão do latex e sistema operacional você tá usando?

**Comment by thiagodnf** [comment]
Acabei de perceber que isso pode ser um problema não da versão do latex, mas do SO.

**Comment by thiagodnf** [comment]
@Renato2012 fiz uma alteração no seu PR. Você poderia ver se ainda tá funcionando?

**Comment by Renato2012** [comment]
> Obrigado @Renato2012
> 
> Você poderia informar qual versão do latex e sistema operacional você tá usando?

Estou usando o Overleaf online.

**Comment by Renato2012** [comment]
> @Renato2012 fiz uma alteração no seu PR. Você poderia ver se ainda tá funcionando?

Sim, funcionou após a alteração.

**Comment by thiagodnf** [comment]
Muito obrigado @Renato2012 . Vou fazer o merge.
