### ISSUE TITLE
Erro ao imprimir Glossário

### ISSUE THREAD

**Issue by Renato2012** [thiagodnf/uecetex2#34]
@thiagodnf , no Overleaf, o glossário (\imprimirglossario) causa o erro da imagem abaixo.
![glossary-error](https://github.com/thiagodnf/uecetex2/assets/9983708/926a8bc7-dc1e-4e94-8249-12c34e982080)

Corrigi o problema, apenas substituindo
_%\renewcommand*{\glossaryentryfield}[5]{%
%	\item[\glstarget{##1}{##2:}] ##3.%
%}%_ 

por (**alteração**)

\renewcommand*{\glossentry}[2]{%
       \item[\glossentryname{##1}:] \glossentrydesc{##1}.%
}%

Usei o **ifplatform**, mas se rodar pra você com a alteração acho que não tem necessidade do uso do **ifplatform**.
![Captura de tela de 2023-10-12 17-59-01](https://github.com/thiagodnf/uecetex2/assets/9983708/a3de9f07-036f-4d85-95b9-46ba9fb86bb6)

Também tive que alterar: _\glossarystyle{glossario-uece}_ por **\setglossarystyle{glossario-uece}**

**Comment by thiagodnf** [comment]
Muito obrigado @Renato2012 . Fix alguns testes aqui no Mac e funcionou tranquilo as suas sugestões.
Você consegue testar esse PR https://github.com/thiagodnf/uecetex2/pull/36?

Você tem o latex instalado no seu computador? Seria bom também testar Windows/Linux...

**Comment by Renato2012** [comment]
@thiagodnf , testei o PR no Overleaf e funcionou tranquilo. 
Creio que o Overleaf esteja hopedado em servidores Linux.

Não tenho o latex instalado em minha máquina, utilizo bastante o Overleaf. Mas posso instalar aqui em breve.

**Comment by thiagodnf** [comment]
Perfeito. Muito obrigado @Renato2012 . Vou fazer o merge .
Sim, acredito que o Overleaf usa Linux também.
