### ISSUE TITLE
Contemplar as alterações da NBR 6023/2018

### ISSUE THREAD

**Issue by Renato2012** [thiagodnf/uecetex2#39]
Olá @thiagodnf 

Percebi que no Guia de Normalização da UECE, as URLs não possuem '<' '>' no início e fim.
![eletronica-ref](https://github.com/thiagodnf/uecetex2/assets/9983708/d663042f-cf2e-474b-83f8-e2cab019c263)

Mas no template as URLs estão delimitadas por '<' '>'.
![eletronica-ref-wrong](https://github.com/thiagodnf/uecetex2/assets/9983708/a505def2-2ae9-40fa-8144-5334060f213e)

Achei uma issue no git da abntex com uma solução (https://github.com/abntex/abntex2/issues/210#issuecomment-570824144). Testei e funcionou bem, no Overleaf.

Notei também que o template não quebra as URLs longas, as quais excedem a margem direita. Resolvi este problema, abrirei outra issue para discutir essa outra questão.

**Comment by thiagodnf** [comment]
Olá @Renato2012 

Obrigado por reportar os erros. Eu testei somente o problema da margem direita. Esse foi o resultado

<img width="449" alt="image" src="https://github.com/thiagodnf/uecetex2/assets/114015/16eb20b3-19c4-4287-8686-382a739517ad">

Esse foi o código. Consegue reproduzir?

```tex
@thesis{kachel2011,
    author    = {Vicente José Kachel},
    title         = {``Projeto Prosperar'' uma proposta de fomento para a administração pública municipal},
    year        = {2011},
    type        = {Trabalho de Conclusão de Curso (Especialização em Gestão Pública)},
    school    = {Universidade Federal do Paraná},
    address = {Curitiba},
    url = {http://dspace.c3sl.ufpr.br:8080/dspace/bitstream/handle/1884/33869/VICENTE%20JOSE%20KACHEL.pdf?sequence=1},
    note = {Acesso em: 22 maio 2014}
}
```

**Comment by Renato2012** [comment]
Olá @thiagodnf 
sim, reproduzi aqui, tive o mesmo resultado que você.

Quando me referi a URL que excede a margem, foi com a seguinte referência:
![ibge-wrong](https://github.com/thiagodnf/uecetex2/assets/9983708/5000be94-82f5-4968-bd47-f27166157d10)

aqui o código bib:

% site de organização.
@misc{ibge23,
 organization = {Instituto Brasileiro de Geografia e Estat{\'i}stica},
 org-short = {IBGE},
 publisher = {Agência IBGE Notícias},
 title = {Em 2022, analfabetismo cai, mas continua mais alto entre idosos, pretos e pardos e no Nordeste},
 year = {2023},
 url = {https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37089-em-2022-analfabetismo-cai-mas-continua-mais-alto-entre-idosos-pretos-e-pardos-e-no-nordeste},
 urlaccessdate = {11 nov. 2023},
}

Resolvi o problema das URLs que excedem a margem de 2 formas diferentes, ambas funcionaram no Overleaf.
**Solução 1:** inserir o seguinte comando no preambulo.tex

%%% Forçar a quebra de url.
\usepackage{url}
\def\UrlBreaks{\do\/\do-}
%%% end.

**Solução 2:** adicionar hyphens no documentclass
\documentclass[        
    a4paper,          % Tamanho da folha A4
    12pt,             % Tamanho da fonte 12pt
    chapter=TITLE,    % Todos os capitulos devem ter caixa alta
    section=TITLE,    % Todas as secoes devem ter caixa alta
    oneside,          % Usada para impressao em apenas uma face do papel
    english,          % Hifenizacoes em ingles
    spanish,          % Hifenizacoes em espanhol
    brazil,            % Ultimo idioma eh o idioma padrao do document
    **hyphens        % Forçar a quebra de URLs que excedem a margem**
]{abntex2}

**Comment by Renato2012** [comment]
Antes das alterações:
![ibge-wrong](https://github.com/thiagodnf/uecetex2/assets/9983708/dcea6bd1-103a-4bbf-8edc-54c66b003a29)

Resultado após as alterações:
![ibge](https://github.com/thiagodnf/uecetex2/assets/9983708/d71eb471-faeb-4d2b-b85a-83daeae10a14)

**Comment by thiagodnf** [comment]
@Renato2012 pode verificar se o pull request funciona pra você? Aqui funcionou. Muito obrigado por reportar (e corrigir) o bug.

**Comment by Renato2012** [comment]
@thiagodnf tudo ok, aqui.

**Comment by thiagodnf** [comment]
Muito obrigado novamente @Renato2012 Acabei de fazer o merge.
