### ISSUE TITLE
Exportar para o formato .doc

### ISSUE THREAD

**Issue by diegommarino** [thiagodnf/uecetex2#5]
Thiago, alguma vez você precisou exportar seu tex para o formato doc ou algum formato que o word leia? Estou precisando fazer isso, mas não encontrei ferramentas que consigam realizar a conversão de forma correta. Se eu tento linha de comando eu recebo erros de compilação, se eu tento ferramentas online (de pdf para doc) o arquivo perde boa parte da formatação.

**Comment by thiagodnf** [comment]
Olá Diego,

A conversão de latex para doc é sempre complicado. Realmente, vários erros aparecem.

Já precisei converter para doc. Dá uma olhada em http://pandoc.org/
Se funcionar, não vai ser perfeito e você vai precisar mexer no doc gerado.

**Comment by ItaloYeltsin** [comment]
sugiro exportar para html e importar o html dentro word

**Comment by thiagodnf** [comment]
Olá @diegommarino, tudo bem?

Conseguiu fazer a conversão?
