### ISSUE TITLE
Como consigo retirar o negrito da palavra "fonte" que fica na margem da legenda de uma figura. 

### ISSUE THREAD

**Issue by misaelira** [thiagodnf/uecetex2#6]
Primeiro quero agradecer seu trabalho, para quem não tem muito conhecimento sobre o Latex  e precisa dele para elaborar o seu TCC, seus pots são muito úteis.

Eu estava com problema com a margem da legenda da figura, no caso queria deixar "figura 1" em negrito, então utilizei o comando  labelfont=bf (segue logo abaixo) que você indicou , mas esse comando está fazendo com que a palavra "fonte" fique em negrito também, como sou aluno da Uece, as normas pedem que a palavra "fonte" não fique em negrito. Se você puder me ajudar agradeço, faz muito tempo que estou tentando concertar e o mais próximo que consegui foi com sua postagem.

% Margen da legenda da figura e da tabela
\captionsetup{
	justification=centering,% Centraliza o caption
	skip=0pt,                %Retira o espaco entre a figura/tabela e o caption
	labelfont=bf, % A palavra 'Figure 1' agora eh negrito
	font=bf	% O texto depois de 'Figure 1' agora eh negrito
}

Outro problema, mas esse não e tão relevante como o anterior, e que comando utilizo pro título da figura ficar em negrito, utilizando o comando  font=bf  ele fica em negrito, mas em compensação o que vem depois da palavra fonte também fica em negrito, o que não é correto em relação as normas da Uece . Agradeço desde já qualquer ajuda.

**Comment by thiagodnf** [comment]
Olá Misaelira, tudo bem?

Obrigado por entrar em contato.

Eu analisei o modelo atual da UECE (Disponível em http://www.uece.br/biblioteca/dmdocuments/GUIA_DE_NORMALIZACAO_UECE__V.1_21_08_2016.pdf) e baixei e compilei a última versão do uecetex2. Percebi que, aparentemente, os dois estão iguais, ou seja, você não precisaria mudar nada com relação aos captions das figuras.

Será que você está usando uma versão antiga do modelo? Você poderia baixar novamente o modelo, compilar e ver se você ainda tem algum problema (Link: https://github.com/thiagodnf/uecetex2/archive/master.zip)?

Estou enviando em anexo a versão que acabei de compilar aqui. 
[documento.pdf](https://github.com/thiagodnf/uecetex2/files/1105661/documento.pdf)

**Comment by misaelira** [comment]
Muito obrigado por responder, você está totalmente correto, eu estava com a
versão antiga (segue em anexo o modelo), vou baixar essa nova versão e
tentar passar meu trabalho pra lá.
você sabe me dizer se mudou os comandos da ultima versao para essa nova?

Em 27 de junho de 2017 11:38, Thiago Nascimento <notifications@github.com>
escreveu:

**Comment by thiagodnf** [comment]
Eu não lembro de ter feito alterações a esse nível. Provalmente você não terá problemas. 

Se funcionar, me avise =D

**Comment by misaelira** [comment]
amigo funcionou, muito obrigado, você me ajudou muito.

2017-06-27 12:56 GMT-03:00 Thiago Nascimento <notifications@github.com>:

**Comment by thiagodnf** [comment]
Ótimo!

Se precisar de ajuda, só entrar em contato.

**Comment by misaelira** [comment]
Olá amigo, surgiu algumas novos problemas, primeiro; como posso mudar o
nome "Lista de ilustrações" para "Lista de figuras".
Segundo; nas figuras temos a seguinte situação (Fonte - Elaborado pelo
autor) como eu tiro o "-" e coloco o ":" para ficar assim (Fonte :
Elaborado pelo autor)
Terceiro; você tem alguma ideia do por que no sumário meu anexo ficou
margem para a direita? (segue o documento em anexo)


2017-06-27 20:00 GMT-03:00 Thiago Nascimento <notifications@github.com>:

**Comment by thiagodnf** [comment]
Olá @misaelira 

Corrigi o problema do "Fonte". Agora é impresso no PDF com ":" e não mais "-".
Para colocar "Lista de Figura" ao invés de "Lista de Ilustrações" você deve colocar o seguinte comando depois do \begin{document}

`\renewcommand{\listfigurename}{Lista de Figuras}`

E por fim, acho que você esqueceu de anexar o documento com o seu problema no sumário.

Obrigado pelo feedback e desculpa a demora.
