### ISSUE TITLE
Bug na lista de abreviaturas e siglas

### ISSUE THREAD

**Issue by WellingtonCosta** [thiagodnf/uecetex2#7]
Ao chamar o comando para imprimir a lista de abreviaturas e siglas, o template exibe apenas uma página em branco.

**Comment by thiagodnf** [comment]
Olá @WellingtonCosta , tudo bem?

Você está usando o texstudio?

**Comment by WellingtonCosta** [comment]
Oi @thiagodnf

**Comment by thiagodnf** [comment]
Estranho Wellington. 

Primeiro que eu acabei de descobrir que tem 2 "uecetex2" no sharelatex. Isso não deveria acontecer. Inclusive vou encontrar em contato com eles para organizar isso.

Segundo, eu criei 2 projetos novos usando como base os 2 uecetex2 e em ambos a lista foi gerada normalmente. Eu não precisei fazer nada, apenas compilar. 

Uma pergunta: vc está fazendo a referencia certa? Por exemplo, vc tem que referenciar pelo menos uma vez no texto algo assim "\acrlong{DATASUS}"

**Comment by WellingtonCosta** [comment]
Eu peguei como base o seu modelo que está aqui no Github e a lista de abreviaturas não foi impressa. Apenas uma pagina em branco foi impressa sem titulo e sem corpo.

Você tem algum email para que eu possa compartilhar o projeto no Sharelatex com você?

**Comment by thiagodnf** [comment]
O ideal seria usar o modelo que eu disponibilizei no sharelatex. Porém, vou repetir os seus passos e ver se consigo reproduzir o mesmo erro.

**Comment by WellingtonCosta** [comment]
Eu acabei de achar o template no Sharelatex que vc mencionou e de fato a lista de abreviaturas foi impressa normalmente. Acho que a versão que estou utilizando deve estar bugada. Vou tentar copiar as coisas que já escrevi para o template do Sharelatex. Creio que irá dar certo.

**Comment by WellingtonCosta** [comment]
Uma dúvida: esse template que está no Sharelatex já está no novo padrão da UECE?

**Comment by thiagodnf** [comment]
Provavelmente sim pois tempos atrás fiz várias modificações que foram solicitadas e pedi para eles atualizarem o sharelatex. Se vc tiver algum problema é só reportar. Inclusive eu estou planejando fazer uma revisão das últimas regras.

**Comment by WellingtonCosta** [comment]
Ok, @thiagodnf. Fico grato pela atenção. Qualquer coisa eu comento aqui. :)

**Comment by thiagodnf** [comment]
Acabei de baixar o arquivo uecetex2-master.zip, subi o arquivo no sharelatex (sem descompactar), mudei o arquivo principal nas configurações para "documento.tex", compilei e a lista apareceu normalmente. =D

**Comment by WellingtonCosta** [comment]
A lista de abreviaturas também apareceu pra mim quando eu utilizei o template uecetex2 que está no Sharelatex, porém quando eu adiciono um novo "\newacronym{xml}{XML}{eXtensible Markup Language}", este não aparece na lista de abreviaturas.

**Comment by WellingtonCosta** [comment]
E quando eu limpei o cache de compilação, a lista de abreviaturas não apareceu mais.

**Comment by thiagodnf** [comment]
Estranho. Talvez esse seja um problema do sharelatex e não do uecetex2.

**Comment by WellingtonCosta** [comment]
Ainda não tive a oportunidade de pegar o meu projeto que está no Sharelatex e testar no TexStudio e ver se o problema da lista de abreviaturas também acontece.

**Comment by thiagodnf** [comment]
Ótimo. Quando tiver tempo tenta fazer isso mesmo para a gente confirmar.

**Comment by WellingtonCosta** [comment]
Vou tentar fazer hoje pela noite e te aviso. :)

**Comment by thiagodnf** [comment]
Ola @WellingtonCosta 

Ainda com o problema?

**Comment by WellingtonCosta** [comment]
Oi, @thiagodnf 

Esqueci de te dar um feedback a respeito do bug...

Bom, o problema da lista de abreviaturas sumir acontece quando eu limpo o cache e recompilo o projeto. Eu acabei deixando isso de lado e estou focando em terminar as partes mais importantes da monografia.

**Comment by thiagodnf** [comment]
Ótimo!

Acabei de fazer um commit onde eu corrigi o problema do "Fonte:". Algumas pessoas estavam reclamando que o "-" estava errado. Depois vou atualizar a versão do sharelatex.

Boa sorte!

**Comment by ItaloYeltsin** [comment]
Olá a todos,

tive o mesmo problema na minha monografia, inclusive no ShareLatex e no TexStudio. A diferença é que no TexStudio tem a opção de Tools > Bibliografia, ou Glossary ou Index que são uma espécie de pré-processamento. Eu utilizava uma dessas três e quando compilava aparecia a lista de abreviaturas.

**Comment by ItaloYeltsin** [comment]
Acabei de ter o mesmo problema no TexStudio. A Lista não estava atualizando. Lembrando que para aparecer na lista de abreviaturas, além de você ter que adicionar o comando <mark>\newacronym{xml}{XML}{eXtensible Markup Language}<mark> em <mark>elementos-pre-textuais/lista-de-abreviaturas-e-siglas.tex </mark>, você deve utilizar pelo menos uma vez no texto esse comando com \acrshort{xml} ou \acrlong{xml}. Caso a sigla não apareça na lista de abreviatuas, no TexStudio, execute <mark>Tools > Glossary" que ela aparecerá </mark>

**Comment by amandaalcantara** [comment]
Uso o TexStudio e a lista de abreviaturas e siglas aparece uma página em branco. Não consegui fazê-la aparecer, mesmo com as dicas. Não sei se sou muito iniciante pra compreender o que foi feito, ou se mesmo assim, não deu certo. Agradeço se puderem me ajudar!

**Comment by amandaalcantara** [comment]
> Uso o TexStudio e a lista de abreviaturas e siglas aparece uma página em branco. Não consegui fazê-la aparecer, mesmo com as dicas. Não sei se sou muito iniciante pra compreender o que foi feito, ou se mesmo assim, não deu certo. Agradeço se puderem me ajudar!
