### ISSUE TITLE
Sumário

### ISSUE THREAD

**Issue by tuliosilveira** [thiagodnf/uecetex2#8]
Olá Thiago,
Como posso reduzir os níveis que aparecem no sumário?
Att.
Túlio Silveira

**Comment by thiagodnf** [comment]
OLá Tulio,

Poderia fornecer um exemplo do que você quer?
Aliás, o modelo da UECE permite isso que você quer?

**Comment by tuliosilveira** [comment]
%Arquivo introducao.tex
\chapter{Introdução}
	\section{Contextualização}
		\subsection{A Crise atual e função-objetivo da organização}
			\paragraph{}
			\paragraph{}
			\paragraph{}
		\subsection{Sustentabilidade}
			\paragraph{}
			\paragraph{}
		\subsection{Aboradgem deterministica}
		\subsection{Abordagem indeterministica}
	\section{Problema de Pesquisa}
		\paragraph{}
		\paragraph{}
	\section{Objetivos}
		\paragraph{}
	\section{Contribuição Científica e Prática Esperada}
		\paragraph{}
		\paragraph{}		
		\paragraph{}
\chapter{Metodologia}
	\paragraph{}
	\paragraph{}
	\paragraph{}
\chapter{Revisão da Literatura}
\chapter{Resultados}
\chapter{Conclusão}

![image](https://user-images.githubusercontent.com/35851054/35472365-e214a1a8-0354-11e8-9956-0fe0a82e235a.png)

**Comment by tuliosilveira** [comment]
Eu gostaria que o sumário apresentasse apenas até o nível 3 (ex. 1.1.1). E qua a seção \paragraph não aparecesse.

**Comment by thiagodnf** [comment]
Olá Tulio,

Você realmente precisa do comando \paragraph{}?

**Comment by tuliosilveira** [comment]
Thiago,

Seria o ideal! Qual seria a outra solução?

Atenciosamente,

Tulio Silveira

2018-01-30 8:02 GMT-02:00 Thiago Nascimento <notifications@github.com>:

**Comment by thiagodnf** [comment]
Ola Tulio,

Coloca o seguinte comando antes do `\begin{document}` 

```
\makeatletter
\renewcommand\l@paragraph[2]{}
\renewcommand\l@subparagraph[2]{}
\makeatother
```

Depois que eu fiz isso o \paragraph{} não foi exibido no sumário porém eu não sei as implicações desse comando no resto do texto. Veja se isso não vai quebrar o seu texto.

**Comment by tuliosilveira** [comment]
Obrigado Thiago!

Funcionou perfeitamente :)

Túlio Silveira

2018-01-30 16:45 GMT-02:00 Thiago Nascimento <notifications@github.com>:

**Comment by tuliosilveira** [comment]
Olá Thiago,

Outra questão que enfrentei utilizando seu modelo é que a lista de
abreviações não está sendo gerada.

Abraços Túlio


Em 4 de fevereiro de 2018 18:16, Tulio Gonçalves da Silveira <
tuliosilveira@gmail.com> escreveu:

**Comment by thiagodnf** [comment]
Ola Tulio,

![untitled](https://user-images.githubusercontent.com/114015/36733146-6dc9ff60-1bae-11e8-8b15-d5590aca2818.png)

Você precisa usar o comando Glossary no menu do TexStudio.
Porem ele só ira funcionar se você tiver instalado o Perl no seu computador.

Caso contrário, a seguinte mensagem aparecerá

makeglossaries.exe: The script engine could not be found. makeglossaries.exe: Data: scriptEngine="perl.exe"

**Comment by nilson-aguiar** [comment]
Outra opção é utilizar o [OverLeaf](https://www.overleaf.com/) vc pode editar seu projeto online e ele compila por lá mesmo.

Tô usando ele junto com o projeto do Tiago para minha monografia.

**Comment by tuliosilveira** [comment]
Obrigado!
