### ISSUE TITLE
Problemas na versão em inglês

### ISSUE THREAD

**Issue by davimonteiro** [thiagodnf/uecetex2#9]
Olá Thiago.

Primeiramente, gostaria de parabenizá-lo pelo seu projeto.

Atualmente estou escrevendo minha dissertação em inglês usando o template uecetex2. Porém, existem alguns problemas que gostaria de relatar:
-O cabeçalho do resumo (versão em português) também fica em ingles (abstract)
-O cabeçalho "LISTA DE ABREVIATURAS E SIGLAS” permanece em português
-O cabeçalho "LISTA DE QUADROS" permanece em português
-O cabeçalho "LISTA DE ALGORITMOS" permanece em português
-O cabeçalho "LISTA DE CODIGOS-FONTE" permanece em português
-O cabeçalho "LISTA DE ABREVIATURAS" permanece em português
-Os ID's dos captions para quadros ("Quadro 1", "Quadro 2"...) permanecem em português
-Problemas com o \citeonline: quando temos trabalhos com dois ou tres autores, visto que aparece o conectivo "e" em português (por exemplo: Fulano 'e' Cicrano (2010))

Atenciosamente,
Davi Monteiro.

**Comment by davimonteiro** [comment]
-O cabeçalho "LISTA DE ABREVIATURAS" permanece em português

**Comment by thiagodnf** [comment]
Olá @davimonteiro 

Muito obrigado pelo feedback.

Fiz algumas correções da biblioteca e melhorei o suporte ao ingles.
Atualize o seu projeto e adicione o seguinte comando depois do \begin{document} 

```tex
\selectlanguage{english}
```

Com relação ao problema do \citeonline eu ainda não consegui encontrar uma forma de resolver.

Caso você encontre mais problemas, por favor me avise

**Comment by frchico** [comment]
@thiagodnf Seria possível utilizar um "abntex2-options.bib" customizado para o inglês para resolver o problema que @davimonteiro falou? 

Se li correto, no pacote abntex2/abntex2cite.sty há uma "sobrecarga" do \bibliography (linha 378 do [arquivo](https://github.com/abntex/abntex2/blob/master/tex/latex/abntex2/abntex2cite.sty)) adicionando um abntex2-options padrão, quando ele não é informado.

Ps.: Ainda estou aprendendo a utilizar o latex para realizar as customizações como as você fez (que por sinal está de parabéns!) para o curso de Sistemas de Informações do IFS/Campus Lagarto.

**Comment by thiagodnf** [comment]
Obrigado pelo feedback @frchico 

Eu tambem fiz algumas sobrecargas no uecetex2 então eu tive que alterar a lib do projeto.
Inclusive, a versao atual já consegue lidar melhor com o ingles. Preciso somente que alguém confirme isso.
Com relacao  ao bib que vc falou, não sei como ela funcionaria agora já que eu fiz a correcao no lib do uecetex2

**Comment by davimonteiro** [comment]
Thiago, o suporte ao inglês melhorou. Entretanto, ainda existe problemas como: 
-O índice do documento possui elementos em português (e.g., Sumário)
-As referências possuem elementos em português (e.g., Disponível em..)

No caso do \citeonline, tive que inserir a citação na mão mesmo e depois colocar um \nocite. Por exemplo: Jaradat, Dearle, and Barker (2013)\nocite{jaradat2013}

**Comment by thiagodnf** [comment]
Olá @davimonteiro 

Coloquei o comando que deixa o documento em ingles no lugar correto. Se a pessoa quer escrever todo em ingles basta retirar o comentário o comando. 

Com relação as referências tenho quase certeza que baixando esse arquivo https://github.com/abntex/abntex2/blob/master/bibtex/bst/abntex2/abntex2-alf.bst, colocando no diretório raiz do projeto, chamando esse estilo já com as modificações talvez funcione

**Comment by thiagodnf** [comment]
Fiz algumas melhorias no suporte ao ingles disponivel no commit https://github.com/thiagodnf/uecetex2/commit/b251d063d8c9a9fa1d1d481315e0d971bbe1ab43

Vou fechar esta issue por inatividade. Mais umavez, obrigado @davimonteiro pelo feedback
